version: '2'

services: 
  nlp-demo:
   image: nsankabathula/nlp-demo:latest
   container_name: nlp-demo-compose
   volumes:
     - '.:/usr/src/app'
     - '/usr/src/app/node_modules'
   ports:
     - 4200:4200
   networks:
     - esnet
networks:
  esnet:     